language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install .
  - pip install docutils pygments  # Used to check package metadata.

script:
  - python setup.py check --strict --metadata --restructuredtext
  - python setup.py test

deploy:
  on:
    python: '3.7'
    tags: true
  provider: pypi
  user: phx
  password:
    secure: "E+K6YCYtaDJKBrZWxDG2o8BMzYmLZsLeaiKTZtYu2q1NSZ+DTs06KGmSR9Wu+lLxoVkZvPNJEPwSDTCe5N0JyOW/MmlzYdWiGB+Q/+9O8s1nHqyvoMN02hpZ9YiC97YtjpZk53DKvrRE6UrS6o6cruzLqyCr3XexYZLujtzZqQJbzmWtx9+SVMQgImKTOtTQxCH9ZELgn+e67Ko+T4ORTUWwROM9HKqJ6TSJjWEfuC6jIt9/D8+YGZpe/F8L3SLO1pkiI7DrrlE17W1QrDDO9dLWX6XWvuLskVtouIUaStfL2m1aRUczS5skYw6kn1rl/m09VfjeG1QR7piNHZC02opnBeauKU+S8RYShSwbrBGBoSqKa+wYnQPg5TI2vjR5fF88VhPPIgK84R3+ROF/dRrRX1ttWFD7xrfJlCBrwK0WqnKLXz6D2NCjpxzi/R/twjKRGuKR210IhKjm0soW9X1Q8+bQqxRIoayYhmMad1zMhSdF3g8+zwCnFr0R9/wF5JaLz35OKGqmWBcrHJ+6Juky1v0NDRI8l/MogeUyIeqUR3N1E5toOLhSfZC347rj+nHZ1Ft6tqO1/LtyyMXHL3ZBGrMGNqO/qe3QnVsr5wECP4EWV2h9c9h8SR3xex9v+9F8App+VKo06ywLsnUVpxnBPY+9mrB6pa3lapBuRBw="
  distributions: 'bdist_wheel sdist'
