# :see: https://peps.python.org/pep-0621/

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "phx-filters-iso"
version = "3.1.0"
description = "Extends phx-filters, adding filters for interpreting ISO codes."
readme = "README.rst"
requires-python = ">= 3.12"
license = { file = "LICENCE.txt" }
authors = [
    { name = "Phoenix Zerin", email = "phx@phx.nz" }
]

keywords = [
    "bcp 47",
    "data validation",
    "i18n",
    "ietf language tags",
    "internationalisation",
    "internationalization",
    "iso",
    "iso-3166",
    "iso-4217",
    "l10n",
    "localisation",
    "localization",
    "standards",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    'Topic :: Text Processing :: Filters',
]

dependencies = [
    'phx-filters >= 3.5.1',
    'iso3166',
    'language_tags',
    'py-moneyed',
]

# https://filters.readthedocs.io/en/latest/extensions.html#registering-your-filters
[project.entry-points."filters.extensions"]
Country = "filters_iso:Country"
Currency = "filters_iso:Currency"
Locale = "filters_iso:Locale"

[project.urls]
Documentation = "https://filters.readthedocs.io/en/latest/extension_filters.html#iso-filters"
Changelog = "https://github.com/todofixthis/filters-iso/releases"
Issues = "https://github.com/todofixthis/filters-iso/issues"
Repository = "https://github.com/todofixthis/filters-iso"

[dependency-groups]
dev = [
    "autohooks>=26,<27",
    "autohooks-plugin-black>=23,<24",
    "autohooks-plugin-ruff>=25,<26",
    "black>=26,<27",
    "pytest>=8,<9",
    "tox>=4,<5",
    "tox-uv>=1.23.0,<2",
]

[tool.autohooks]
mode = "pythonpath"
pre-commit = [
    "autohooks.plugins.black",
    "autohooks.plugins.ruff",
]

[tool.hatch.build.targets.sdist]
include = [
    "filters_iso",
    "LICENCE.txt",
    "test",
]

[tool.hatch.build.targets.wheel]
include = ["filters_iso"]

[tool.tox]
env_list = ["py314", "py313", "py312"]

[tool.tox.env_run_base]
commands = [["pytest"]]
runner = "uv-venv-lock-runner"

[tool.uv]
keyring-provider = "subprocess"
